import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Features from "./components/features/Features";
import GroupEngagement from "./components/groupEngagement/GroupEngagement";
import Instructors from "./components/instructors/Instructors";
import Pointers from "./components/pointers/Pointers";
import ExclusiveFeature from "./components/exclusiveFeature/ExclusiveFeature";
import CourseDetails from "./components/courseDetails/CourseDetails";
import Sidebar from "./components/sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <main className="">
          <div className="text-white relative  bg-gradient-to-r from-[#030917] to-[#102759]">
            <Header />
          </div>
          <div className=" xl:max-w-7/12  lg:grid lg:grid-cols-12 gap-4 mx-auto mt-10 space-y-10">
            <aside className="lg:col-span-8  p-4 space-y-10">
              <Instructors />
              <Features />
              <GroupEngagement />
              <Pointers></Pointers>
              <ExclusiveFeature />
              <CourseDetails></CourseDetails>
            </aside>
            <aside className="lg:col-span-4 xl:ml-30 2xl:ml-0  p-4 hidden xl:block">
              <div className=" absolute top-10 ">
                <Sidebar />
              </div>
            </aside>
          </div>
        </main>
        {children}
        <Footer />
      </body>
    </html>
  );
}
