import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Features from "./components/features/Features";
import GroupEngagement from "./components/groupEngagement/GroupEngagement";
import Instructors from "./components/instructors/Instructors";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Navbar />
        <main className="max-w-8/12 mx-auto mt-10 space-y-10">
          <Header />
          <Instructors />
          <Features />
          <GroupEngagement />
        </main>
        {children}
        <Footer />
      </body>
    </html>
  );
}
